CREATE TABLE IF NOT EXISTS COMMENTS (
  id SERIAL PRIMARY KEY,
  userid VARCHAR(225) NOT NULL,
  commented TEXT NOT NULL,
  postid VARCHAR(255) NOT NULL,
  FOREIGN KEY (userid) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (postid) REFERENCES posts(id) ON DELETE CASCADE
);
