CREATE TABLE IF NOT EXISTS posts (
  id VARCHAR(100) PRIMARY KEY NOT NULL,
  title VARCHAR(50) NOT NULL,
  description TEXT NOT NULL,
  createdat TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedat TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE TRIGGER update_updatedat 
BEFORE UPDATE ON posts 
FOR EACH ROW EXECUTE FUNCTION update_updated_at();
