import torch
import torch.nn as nn
from torch.nn.modules import Conv2d, ReLU

"""

We are defining two models here:

    ModelOneGen: Generator
    ModelFighter: Discriminator

    I am Following the GAN's Model where:
        We send images from two different sources, one is the real image, other is generated by Generator (ModelOneGen)
        Discrimintors Job is to correctly classify the real image as true(real) and generated image as false(fake)

        
    Therefore,
        Generator and Discriminator in this case will be CNNs (Convolutional Neural Network)
        Generator will take an grayscale image as input and output rgb image 
        Discriminator will take rgb image and decide which one is fake or real

        Here the goal will be to min max, where generator is trying to maximize its goal of being identified as the real image
        While the discriminator is trying to minimize the loss by classifying generated image as real

        

"""

class ModelOneGen(nn.Module):
    """
        ModelOneGen: Better ModelOne

        Going to use UNet architecture; for auto colorization....
        
    """
    def __init__(self):
        
        super(ModelOneGen,self).__init__()

        # Encoders
        self.e1 = self.encoder_block(1,64)
        self.e2 = self.encoder_block(64, 128)
        self.e3 = self.encoder_block(128, 256)
        self.e4 = self.encoder_block(256,512)
        self.e5 = self.encoder_block(512, 1024)
        self.e6 = self.encoder_block(1024,2048)

        # Decoders
        self.u5 = self.up_block(2048, 1024)
        self.d5 = self.decoder_block(2048, 1024)
        
        self.u4 = self.up_block(1024, 512)
        self.d4 = self.decoder_block(1024, 512)

        self.u3 = self.up_block(512, 256)
        self.d3 = self.decoder_block(512, 256)

        self.u2 = self.up_block(256, 128)
        self.d2 = self.decoder_block(256, 128)
        
        self.u1 = self.up_block(128, 64)
        self.d1 = self.decoder_block(128, 64)

        self.final = nn.Conv2d(64, 3, kernel_size=1)
        self.tanh = nn.Tanh()

    def forward(self, x):
        e1 = self.e1(x)
        e2 = self.e2(e1)
        e3 = self.e3(e2)
        e4 = self.e4(e3)
        e5 = self.e5(e4)
        e6 = self.e6(e5)

        d5 = self.u5(e6)
        d5 = torch.cat((e5, d5), dim=1)
        d5 = self.d5(d5)

        d4 = self.u4(d5)
        d4 = torch.cat((e4, d4), dim=1)
        d4 = self.d4(d4)

        d3 = self.u3(d4)
        d3 = torch.cat((e3, d3), dim=1)
        d3 = self.d3(d3)

        d2 = self.u2(d3)
        d2 = torch.cat((e2, d2), dim=1)
        d2 = self.d2(d2)
        
        d1 = self.u1(d2)
        d1 = torch.cat((e1, d1), dim=1)
        d1 = self.d1(d1)       


        out = self.final(d1)

        return self.tanh(out)

    def encoder_block(self, input_shape: int, output_shape: int):
        return nn.Sequential(
                nn.Conv2d(input_shape, output_shape, kernel_size=3, padding=1),
                nn.ReLU(),
                nn.Conv2d(output_shape, output_shape, kernel_size=3, padding=1),
                nn.ReLU(),
                nn.MaxPool2d(2)
                )
    
    def up_block(self, input_shape: int, output_shape: int):
        return nn.ConvTranspose2d(input_shape, output_shape, kernel_size=2, stride=2)

    def decoder_block(self, input_shape: int, output_shape: int):
        return nn.Sequential(
                nn.Conv2d(input_shape, output_shape, kernel_size=3, padding=1),
                nn.ReLU(),
                nn.Conv2d(output_shape, output_shape, kernel_size=3, padding=1),
                nn.ReLU(),
                )


class ModelOneGen2(nn.Module):

    """
        ModelOneGen: Better ModelOne

        Going to use UNet architecture; for auto colorization....
        
    """
    def __init__(self):
        
        super(ModelOneGen2,self).__init__()

        # Encoders
        self.e1 = self.encoder_block(1,64)
        self.e2 = self.encoder_block(64, 128)
        self.e3 = self.encoder_block(128, 256)
        self.e4 = self.encoder_block(256,512)
        self.e5 = self.encoder_block(512, 1024)

        # Decoders
        self.u4 = self.up_block(1024, 512)
        self.d4 = self.decoder_block(1024, 512)
        
        self.u3 = self.up_block(512, 256)
        self.d3 = self.decoder_block(512, 256)

        self.u2 = self.up_block(256, 128)
        self.d2 = self.decoder_block(256, 128)

        self.u1 = self.up_block(128, 64)
        self.d1 = self.decoder_block(128, 64)

        self.final = nn.Conv2d(64, 3, kernel_size=1)
        self.tanh = nn.Tanh()

    def forward(self, x):
        e1 = self.e1(x)
        e2 = self.e2(e1)
        e3 = self.e3(e2)
        e4 = self.e4(e3)
        e5 = self.e5(e4)


        d4 = self.u4(e5)
        d4 = torch.cat((e4, d4), dim=1)
        d4 = self.d4(d4)

        d3 = self.u3(d4)
        d3 = torch.cat((e3, d3), dim=1)
        d3 = self.d3(d3)

        d2 = self.u2(d3)
        d2 = torch.cat((e2, d2), dim=1)
        d2 = self.d2(d2)
        
        d1 = self.u1(d2)
        d1 = torch.cat((e1, d1), dim=1)
        d1 = self.d1(d1)       


        out = self.final(d1)

        return self.tanh(out)

    def encoder_block(self, input_shape: int, output_shape: int):
        return nn.Sequential(
                nn.Conv2d(input_shape, output_shape, kernel_size=3, padding=1),
                nn.ReLU(),
                nn.Conv2d(output_shape, output_shape, kernel_size=3, padding=1),
                nn.ReLU(),
                nn.MaxPool2d(2)
                )
    
    def up_block(self, input_shape: int, output_shape: int):
        return nn.ConvTranspose2d(input_shape, output_shape, kernel_size=2, stride=2)

    def decoder_block(self, input_shape: int, output_shape: int):
        return nn.Sequential(
                nn.Conv2d(input_shape, output_shape, kernel_size=3, padding=1),
                nn.ReLU(),
                nn.Conv2d(output_shape, output_shape, kernel_size=3, padding=1),
                nn.ReLU(),
                )


class ModelOneGenX(nn.Module):
    def __init__(self):
        super(ModelOneGenX, self).__init__()

        self.blocks = (1, 32, 64, 128, 256, 512)
            
        self.encoders = nn.ModuleList([
            self.encoder_block(self.blocks[i], self.blocks[i+1]) for i in range(len(self.blocks)-1)
            ])
        
        self.b = self.bottleneck(self.blocks[-1],self.blocks[-1])

        self.decoders = nn.ModuleList([
            self.decoder_block(self.blocks[i] * 2, self.blocks[i-1]) for i in range(len(self.blocks)-1, 1, -1)
            ])
        self.final = self.final_block(64,3)

        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        
        skip_connections = []

        for encoder in self.encoders:
            x = encoder(x)
            skip_connections.append(x)


        x = self.b(x)

        for decoder, skip in zip(self.decoders, reversed(skip_connections)):
            x = torch.cat([x, skip], dim=1)
            x = decoder(x)

        x = torch.cat([x, skip_connections[0]], dim=1)
        x = self.final(x)

        return x


    def encoder_block(self, in_channel: int, out_channel: int, groups: int = 8):
        return nn.Sequential(
                nn.Conv2d(in_channel, out_channel, kernel_size=3, padding=1, stride=1),
                nn.InstanceNorm2d(out_channel),
                nn.LeakyReLU(0.2, inplace=True),

                nn.Conv2d(out_channel, out_channel, kernel_size=3, padding=1, stride=1),
                nn.InstanceNorm2d(out_channel),
                nn.LeakyReLU(0.2, inplace=True),

                nn.MaxPool2d(2)
                )
    
    def bottleneck(self, in_channel: int, out_channel: int):
        return nn.Sequential(
                nn.Conv2d(in_channel, out_channel, kernel_size=3, padding=1),
                nn.Tanh()
                )

    def decoder_block(self, in_channel: int, out_channel: int, groups: int = 8):
        return nn.Sequential(
                nn.ConvTranspose2d(in_channel, out_channel, kernel_size=3, stride=2, padding=1,output_padding=1),
                nn.BatchNorm2d(out_channel),
                nn.ReLU(),
                nn.ConvTranspose2d(out_channel, out_channel, kernel_size=3, padding=1),
                nn.BatchNorm2d(out_channel),
                nn.ReLU()
                )
    
    def final_block(self, in_channel: int, out_channel: int):
        return nn.Sequential(
                nn.ConvTranspose2d(in_channel, out_channel, kernel_size=3, stride=2, padding=1,output_padding=1),
                nn.ReLU(),
                nn.ConvTranspose2d(out_channel, out_channel, kernel_size=3, stride=1, padding=1),
                nn.Tanh()
                )

class ModelFighter2(nn.Module):
    def __init__(self):
        super(ModelFighter2, self).__init__()

        self.groups = 8
        self.model = nn.Sequential(
                           # First convolutional layer
            nn.Conv2d(3, 64, kernel_size=4, stride=2, padding=1),  # Output size: (batch, 64, h/2, w/2)
            nn.LeakyReLU(0.2, inplace=True),  # Leaky ReLU activation function
            # Second convolutional layer
            nn.Conv2d(64, 128, kernel_size=4, stride=2, padding=1),  # Output size: (batch, 128, h/4, w/4)
            nn.GroupNorm(self.groups,128),  # Batch Normalization
            nn.LeakyReLU(0.2, inplace=True),
            
            # Third convolutional layer
            nn.Conv2d(128, 256, kernel_size=4, stride=2, padding=1),  # Output size: (batch, 256, h/8, w/8)
            nn.GroupNorm(self.groups,256),
            nn.LeakyReLU(0.2, inplace=True),
            
            # Fourth convolutional layer
            nn.Conv2d(256, 512, kernel_size=4, stride=2, padding=1),  # Output size: (batch, 512, h/16, w/16)
            nn.GroupNorm(self.groups,512),
            nn.LeakyReLU(0.2, inplace=True),
            
            # Fifth convolutional layer
            nn.Conv2d(512, 1, kernel_size=4, stride=2, padding=1),  # Output size: (batch, 1, h/32, w/32)
                )

    def forward(self,x):
        return self.model(x)


class ModelFighter(nn.Module):
    def __init__(self):
        super(ModelFighter,self).__init__()

        self.model = nn.Sequential(
            nn.Conv2d(3, 32, kernel_size=7, stride=1),
            nn.LeakyReLU(0.2, inplace=True),
            nn.Conv2d(32, 32, kernel_size=7, stride=1),
            nn.LeakyReLU(0.2, inplace=True),
            nn.MaxPool2d(kernel_size=2),

            nn.Conv2d(32, 64, kernel_size=5, stride=1),
            nn.LeakyReLU(0.2, inplace=True),
            nn.Conv2d(64, 64, kernel_size=5, stride=1),
            nn.LeakyReLU(0.2, inplace=True),
            nn.MaxPool2d(kernel_size=2),

            nn.Conv2d(64, 128, kernel_size=3, stride=1),
            nn.LeakyReLU(0.2, inplace=True),
            nn.Conv2d(128,128, kernel_size=3, stride=1),
            nn.LeakyReLU(0.2, inplace=True),
            nn.MaxPool2d(kernel_size=2),
            
            nn.Conv2d(128, 256, kernel_size=3, stride=1),
            nn.LeakyReLU(0.2, inplace=True),
            nn.Conv2d(256,256, kernel_size=3, stride=1),
            nn.LeakyReLU(0.2, inplace=True),
            nn.MaxPool2d(kernel_size=2),
            
            nn.Flatten(),
            
            nn.Linear(30976, 512),  
            nn.ReLU(),
            nn.Linear(512, 128),
            nn.ReLU(),
            nn.Linear(128, 16),
            nn.ReLU(),
            nn.Linear(16, 1),
        )

    def forward(self,x):
        return self.model(x)
